blog/urls.py
from django.urls import path
from . import views

urlpatterns = [ 
    path('', views.index, name="index"),
    path('news/', views.news, name="news"),
    path('search/', views.search, name="search"),
    path('news/<slug:slug>/', views.post_detail, name="post_detail_url"),
    path('news/<slug:slug>/leave_comment/', views.comment, name='comment'),
    path('categories/', views.categories, name="categories"),
    path('categories/<slug:slug>/', views.category_detail, name="category_detail_url"),
    path('register/', views.register, name="register"),
    path('contact/', views.contact, name="contact"),
    path('popular/', views.popular, name="popular"),
]

gamma/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.shortcuts import reverse
from django.utils import timezone

class Category(models.Model):
    title = models.CharField('Заголовок', max_length=255)
    slug = models.SlugField('Ссылка', unique=True)
    image = models.ImageField('Картинка', null=True, blank=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
    
    def get_absolute_url(self):
        return reverse('category_detail_url', kwargs={'slug':self.slug})

    def __str__(self):
        return self.title

class Post(models.Model):
    title = models.CharField('Заголовок', max_length=255)
    slug = models.SlugField('Ссылка', unique=True)
    category = models.ForeignKey(Category, on_delete = models.CASCADE, null=True, verbose_name="Категория")
    summary = models.TextField('Краткое описание')
    text = models.TextField('Описание')
    views = models.IntegerField('Просмотры', default=0)
    image = models.ImageField('Картинка', null=True, blank=True)
    date = models.DateTimeField('Дата', default = timezone.now)

    class Meta:
        verbose_name = "Новость"
        verbose_name_plural = "Новости"

    def get_absolute_url(self):
        return reverse('post_detail_url', kwargs={'slug':self.slug})

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Пост')
    author_name = models.CharField('Имя автора', max_length=255)
    comment_text = models.TextField('Текст комментария')
    date = models.DateTimeField('Дата', default=timezone.now)

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.author_name

class FeedBack(models.Model):
    name = models.CharField('Ф.И.О.', max_length=255)
    phone = models.CharField('Телефон', max_length=255)
    email = models.EmailField('Email')
    text = models.TextField('Сообщение')
    date = models.DateTimeField('Дата', default=timezone.now)

    class Meta:
        verbose_name='Сообщение'
        verbose_name_plural='Сообщения'

    def __str__(self):
        return self.name

blog/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    username = forms.CharField(label="Никнейм", required=True, widget=forms.TextInput(attrs={'class':'form-control footer-input margin-b-20'}))
    password1 = forms.CharField(label="Пароль", required=True, widget=forms.PasswordInput(attrs={'class':'form-control footer-input margin-b-20'}))
    password2 = forms.CharField(label="Подтверждение", required=True, widget=forms.PasswordInput(attrs={'class':'form-control footer-input margin-b-20'}))
    email = forms.EmailField(label='Email', required=True, widget=forms.TextInput(attrs={'class':'form-control footer-input margin-b-20'}))
    first_name = forms.CharField(label="Имя", required=True, widget=forms.TextInput(attrs={'class':'form-control footer-input margin-b-20'}))
    last_name = forms.CharField(label="Фамилия", required=True, widget=forms.TextInput(attrs={'class':'form-control footer-input margin-b-20'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2',)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()
        return user

blog/views.py
from django.shortcuts import render, redirect, reverse
from django.db.models import Q
from .models import Post, Category, Comment, FeedBack
from .forms import RegisterForm

def index(request):
    popular = Post.objects.filter(views__gt = 10)[:3]
    return render(request, 'news/index.html', {'popular':popular})

def news(request):
    posts = Post.objects.order_by('-date')
    return render(request, 'news/news.html', {'posts':posts})

def popular(request):
    if request.method == 'POST':
        result = request.POST.get('popular')
        posts = Post.objects.order_by(result)
        return render(request, 'news/news.html', {'posts':posts})
    return redirect('news')

def categories(request):
    categories = Category.objects.order_by('title')
    return render(request, 'news/categories.html', {'categories': categories})

def search(request):
    query = request.GET.get('search')
    search_result = Post.objects.filter(
        Q(title__icontains = query)
    )

    return render(request, 'news/search.html', {'posts': search_result, 'q': query})

def post_detail(request, slug):
    post = Post.objects.get(slug__iexact = slug)
    post.views += 1
    post.save()
    return render(request, 'news/post_detail.html', {'post':post})


def category_detail(request, slug):
    category = Category.objects.get(slug__iexact = slug)
    return render(request, 'news/category_detail.html', {'category':category})

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = RegisterForm()
    return render(request, 'news/register.html', {'form':form})

def comment(request, slug):
    post = Post.objects.get(slug__exact = slug)
    if request.user.is_authenticated:
        post.comment_set.create(
            author_name = request.user.first_name,
            comment_text = request.POST.get('text')
        )
    else:
        post.comment_set.create(
            author_name = request.POST.get('name'),
            comment_text = request.POST.get('text')
        )
    return redirect(reverse('post_detail_url', args = (slug,)))

def contact(request):
    if request.method == 'POST':
        FeedBack.objects.create(
            name = request.POST.get('name'),
            phone = request.POST.get('phone'),
            email = request.POST.get('email'),
            text = request.POST.get('text'),
        )
        return redirect('contact')
    return render(request, 'news/contact.html')

blog/templates/news/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Сайт{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'index' %}">Главная</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'news' %}">Новости</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'categories' %}">Категории</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'contact' %}">Обратная связь</a>
                </li>
                {% if not user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'register' %}">Регистрация</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'login' %}">Войти</a>
                </li>
                {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
                </li>
                {% endif %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Dropdown
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                  </div>
                </li>
              </ul>
              <form class="form-inline my-2 my-lg-0" action="{% url 'search' %}" method="GET">
                <input class="form-control mr-sm-2" name="search" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
              </form>
            </div>
          </nav>
    </header>
    {% block content %}
    {% endblock %}
    <footer>
        футер
    </footer>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

blog/templates/news/categories.html
{% extends 'news/base.html' %}

{% block title %}Категории{% endblock %}
{% block content %}
<section class="container">
    <h1>Все категории</h1>
    <hr>
    <div class="row">
        {% for category in categories %}
            <div class="col-md-3" style="text-align: center;">
                <a href="{{category.get_absolute_url}}">
                    <p>{{category.title}}</p>
                </a>
            </div>
        {% endfor %}
    </div>
</section>
{% endblock %}

blog/templates/news/category_detail.html
{% extends 'news/base.html' %}

{% block title %}{{category.title}}{% endblock %}
{% block content %}
<section class="container">
    <h1>Последние новости в категории: {{category.title}}</h1>
    <div class="row">
        {% for post in category.post_set.all %}
        <div class="col-md-4">
            <div class="card" style="width: 18rem;">
              <a href="{{post.get_absolute_url}}">
                {% if post.image.url != null %}
                <img src="{{post.image.url}}" class="card-img-top" alt="...">
                {% endif %}
              </a>
                <div class="card-body">
                  <h5 class="card-title">{{post.title}}</h5>
                  <a href="{{post.category.get_absolute_url}}">
                    <p class="card-title">{{post.category.title}}</p>
                  </a>
                  <p class="card-text">{{post.summary}}</p>
                  <a href="#" class="btn btn-primary">Читать далее...</a>
                </div>
              </div>
        </div>
        {% endfor %}
    </div>
</section>
{% endblock %}

blog/templates/news/contact.html
{% extends 'news/base.html' %}

{% block title %}Свяжитесь с нами!{% endblock %}
{% block content %}
<section class="container">
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
          <h1 class="display-4">Обратная связь</h1>
          <p class="lead">Оставьте свое сообщение и мы ответим вам (нет)!</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <form action="{% url 'contact' %}" method="POST">
                {% csrf_token %}
                <label for="">Ф.И.О.</label>
                <input type="text" name="name" class="form-control">
                <label for="">Телефон</label>
                <input type="text" name="phone" class="form-control">
                <label for="">Email</label>
                <input type="email" name="email" class="form-control">
                <label for="">Сообщение</label>
                <textarea name="text" class="form-control"></textarea>
                <button class="btn btn-outline-dark">Отправить</button>
            </form>
        </div>
        <div class="col-md-6">
            <h3>Наш адрес:</h3>
            <p>Улица Пушкина, дом Колотушкина</p>
            <h3>Телефоны:</h3>
            <p>88005553535</p>
            <p>+71492286915</p>
        </div>
    </div>
</section>
{% endblock %}

blog/templates/news/index.html
{% extends 'news/base.html' %}

{% block title %}Главная{% endblock %}
{% block content %}
<h1>ДОРОВА МИР!</h1>
<section class="container">
    <div class="row">
        {% for post in popular %}
        <div class="col-md-4">
            <div class="card" style="width: 18rem;">
              <a href="{{post.get_absolute_url}}">
                {% if post.image.url != null %}
                <img src="{{post.image.url}}" class="card-img-top" alt="...">
                {% endif %}
              </a>
                <div class="card-body">
                  <h5 class="card-title">{{post.title}}</h5>
                  <a href="{{post.category.get_absolute_url}}">
                    <p class="card-title">{{post.category.title}}</p>
                  </a>
                  <p class="card-text">{{post.summary}}</p>
                  <a href="#" class="btn btn-primary">Читать далее...</a>
                  <span>Просмотров: {{post.views}}</span>
                </div>
              </div>
        </div>
        {% endfor %}
    </div>
</section>
{% endblock %}

blog/templates/news/news.html
{% extends 'news/base.html' %}

{% block title %}Новости{% endblock %}
{% block content %}
<section class="container">
    <h1>Последние новости</h1>
    <p>Отфильтровать по популярным</p>
    <form action="{% url 'popular' %}" method="POST">
      {% csrf_token %}
      <select name="popular" id="">
        <option value="-views">Популярные</option>
        <option value="-date">По новизне</option>
        <option value="date">Сначала старые</option>
        <option value="views">Не популярные</option>
      </select>
      <button class="btn btn-outline-danger">Фильтровать</button>
    </form>
    <div class="row">
        {% for post in posts %}
        <div class="col-md-4">
            <div class="card" style="width: 18rem;">
              <a href="{{post.get_absolute_url}}">
                {% if post.image.url != null %}
                <img src="{{post.image.url}}" class="card-img-top" alt="...">
                {% endif %}
              </a>
                <div class="card-body">
                  <h5 class="card-title">{{post.title}}</h5>
                  <a href="{{post.category.get_absolute_url}}">
                    <p class="card-title">{{post.category.title}}</p>
                  </a>
                  <p class="card-text">{{post.summary}}</p>
                  <a href="#" class="btn btn-primary">Читать далее...</a>
                  <span>Просмотров: {{post.views}}</span>
                </div>
              </div>
        </div>
        {% endfor %}
    </div>
</section>
{% endblock %}

blog/templates/news/post_detail.html
{% extends 'news/base.html' %}

{% block title %}
{{post.title}}
{% endblock %}
{% block content %}
<h1>{{post.title}}</h1>
{% if post.image.url != null %}
    <img src="{{post.image.url}}" alt="">
{% endif %}
<p>
    Просмотров: {{post.views}}
</p>
<p>
    {{post.text|safe}}
</p>
<p>
    <em>{{post.date|date:'d F, Y'}}</em>
</p>
<hr>
<h3>Оставьте комментарий!</h3>
<form action="{% url 'comment' post.slug %}" method="POST">
    {% csrf_token %}
    {% if not user.is_authenticated %}
    <label for="">Ваше имя:</label>
    <input name="name" type="text" class="form-control">
    {% endif %}
    <label for="">Комментарий</label>
    <textarea name="text" class="form-control"></textarea>
    <button class="btn btn-outline-danger">Отправить</button>
</form>
<hr>
<h2>Комментарев: {{post.comment_set.count}}</h2>
{% for comment in post.comment_set.all %}
    <p>{{comment.author_name}}</p>
    <p>{{comment.comment_text}}</p>
    <p><em>{{comment.date|date:'d F, Y| h:m'}}</em></p>
{% endfor %}
{% endblock %}

blog/templates/news/register.html
{% extends 'news/base.html' %}

{% block title %}Регистрация{% endblock %}
{% block content %}
<section class="container">
    <div class="row">
        <div class="col-md-12">
            <form action="{% url 'register' %}" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-outline-dark">Регистрация</button>
            </form>
        </div>
    </div>
</section>
{% endblock %}

blog/templates/news/search.html
{% extends 'news/base.html' %}

{% block title %}
{{q}}
{% endblock %}
{% block content %}
<section class="content">
    <h1>Поиск по: {{q}}</h1>
    <div class="row">
        {% for post in posts %}
        <div class="col-md-4">
            <div class="card" style="width: 18rem;">
                {% if post.image.url != null %}
                <img src="{{post.image.url}}" class="card-img-top" alt="...">
                {% endif %}
                <div class="card-body">
                  <h5 class="card-title">{{post.title}}</h5>
                  <p class="card-text">{{post.summary}}</p>
                  <a href="#" class="btn btn-primary">Читать далее...</a>
                </div>
              </div>
        </div>
        {% endfor %}
    </div>
</section>
{% endblock %}